/*
 * A dungeon tileset for the hex wave function, and the rules it collapses by.
 *
 * mxgmn's `SimpleTiledModel` reads a tileset as a list of tiles plus an
 * explicit list of legal neighbour PAIRS — `<neighbor left="corner 1"
 * right="empty"/>`, hundreds of lines of it, generated by hand or by a tool.
 * That is the right shape when the tiles are bitmaps and adjacency is whatever
 * the artist decided looks continuous.
 *
 * These tiles are not bitmaps. Every one of them is a hex cell with six edges,
 * and an edge either has an opening in it or it does not — so adjacency is not
 * a list at all, it is a rule: two tiles may sit next to each other when the
 * edges they present to each other AGREE. Deriving the propagator from six
 * sockets per tile rather than listing it gets the same table with none of the
 * bookkeeping, and it is why a thirteen-line tileset below expands to sixty-one
 * tiles and around two thousand legal pairs without anybody typing them.
 *
 * Three socket kinds, and the reason there are three rather than two:
 *
 *   .  wall       solid between the two cells
 *   c  corridor   a passage one tile wide
 *   r  room       open floor continuing into the next tile
 *
 * With only "open" and "shut" the model has no way to tell a corridor from a
 * room, and what comes out is a random open subgraph of the hex grid — the same
 * undifferentiated sponge the noise carve gives, with more machinery. Making
 * `c` and `r` refuse to meet is what forces the two vocabularies apart: rooms
 * can only grow into rooms, corridors can only continue as corridors, and the
 * only way between them is a tile that has one of each, which is a DOOR. The
 * rooms, the corridors and the doors are all consequences of that one rule.
 *
 * Rotation is not authored either. A hex tile has six rotations, so each spec
 * below is expanded into its distinct ones — `hall` has three, because a
 * straight passage is the same passage after half a turn — and the weights are
 * per-rotation so a symmetric tile does not quietly get more of the budget.
 */

/** wall, corridor, room. The numbers are only ever compared for equality. */
export const SOCKET_WALL = 0;
export const SOCKET_CORRIDOR = 1;
export const SOCKET_ROOM = 2;

export interface TileSpec {
	readonly name: string;
	/**
	 * Six sockets as characters, edge `d` facing `AXIAL_DIRECTIONS[d]` — east
	 * first, then anticlockwise.
	 */
	readonly edges: string;
	readonly kind: 'rock' | 'floor';
	/** Relative frequency, per rotation. */
	readonly weight: number;
	readonly color: number;
}

/** One rotation of one spec: what the solver actually places. */
export interface Tile {
	readonly name: string;
	readonly spec: TileSpec;
	readonly rotation: number;
	/** Six socket kinds, already rotated. */
	readonly sockets: readonly number[];
	readonly weight: number;
}

const ROCK = 0x36322c;
const ROOM_FLOOR = 0x8a7c62;
const ROOM_EDGE = 0x7d7059;
const CORRIDOR = 0x6a6152;

/**
 * The tileset.
 *
 * Weights are the whole character of the output and are worth reading as a
 * budget rather than as thirteen independent numbers. Rock outweighs everything
 * because a dungeon is mostly not dungeon; the room family outweighs the
 * corridor family because chambers should be the destination and passages the
 * way between them; and the junctions and the dead end are deliberately scarce,
 * because a level where every third tile is a Y-junction reads as a maze rather
 * than as a place.
 *
 * `dead-end` is here at all — at the lowest weight in the set — because without
 * it every corridor must eventually arrive somewhere, and the solver's only way
 * to satisfy that in a tight spot is to fail. A cheap escape valve costs a few
 * stubs and buys a large drop in contradictions.
 */
export const DUNGEON_TILES: readonly TileSpec[] = [
	{ name: 'rock', edges: '......', kind: 'rock', weight: 14, color: ROCK },

	{ name: 'chamber', edges: 'rrrrrr', kind: 'floor', weight: 5, color: ROOM_FLOOR },
	{ name: 'chamber-wall', edges: 'rrrrr.', kind: 'floor', weight: 4, color: ROOM_EDGE },
	{ name: 'chamber-bay', edges: 'rrrr..', kind: 'floor', weight: 3, color: ROOM_EDGE },
	{ name: 'chamber-nub', edges: 'rrr...', kind: 'floor', weight: 1.2, color: ROOM_EDGE },

	{ name: 'door', edges: 'rrrr.c', kind: 'floor', weight: 1.6, color: 0x9a7d4a },
	{ name: 'mouth', edges: 'rrr..c', kind: 'floor', weight: 1.2, color: 0x9a7d4a },

	{ name: 'hall', edges: 'c..c..', kind: 'floor', weight: 4, color: CORRIDOR },
	{ name: 'bend-wide', edges: 'c.c...', kind: 'floor', weight: 2.5, color: CORRIDOR },
	{ name: 'bend-tight', edges: 'cc....', kind: 'floor', weight: 1.6, color: CORRIDOR },
	{ name: 'fork', edges: 'c.c.c.', kind: 'floor', weight: 1.2, color: 0x5f5748 },
	{ name: 'tee', edges: 'cc.c..', kind: 'floor', weight: 0.9, color: 0x5f5748 },
	{ name: 'dead-end', edges: 'c.....', kind: 'floor', weight: 0.5, color: 0x5a5245 },
];

function socketOf(character: string): number {
	if (character === 'c') return SOCKET_CORRIDOR;
	if (character === 'r') return SOCKET_ROOM;
	if (character === '.') return SOCKET_WALL;
	throw new Error(`unknown socket '${character}'`);
}

/**
 * Every distinct rotation of every spec.
 *
 * A rotation by `k` steps anticlockwise carries the socket on edge `d - k` onto
 * edge `d`, which is the one line here that a sign error would hide in: get it
 * backwards and the tileset still expands to the same COUNT of tiles, still
 * solves, and produces corridors that turn the wrong way at every bend. The
 * check that catches it is `hall` — a straight passage must come out with three
 * rotations, not six.
 */
export function expandTiles(specs: readonly TileSpec[] = DUNGEON_TILES): Tile[] {
	const tiles: Tile[] = [];

	for (const spec of specs) {
		if (spec.edges.length !== 6) throw new Error(`${spec.name} needs six sockets`);
		const base = [...spec.edges].map(socketOf);
		const seen = new Set<string>();

		for (let k = 0; k < 6; k++) {
			const sockets = base.map((_, d) => base[(d - k + 6) % 6]!);
			const signature = sockets.join('');
			if (seen.has(signature)) continue;
			seen.add(signature);
			tiles.push({
				name: `${spec.name} ${k}`,
				spec,
				rotation: k,
				sockets,
				weight: spec.weight,
			});
		}
	}

	return tiles;
}

/** `allowed[d][t]` — every tile that may sit in direction `d` from tile `t`. */
export type Propagator = readonly (readonly Int32Array[])[];

/**
 * The adjacency table, derived from the sockets.
 *
 * The symmetry the solver depends on — `t2 ∈ allowed[d][t1]` exactly when
 * `t1 ∈ allowed[d+3][t2]` — is not asserted here, it is structural: both
 * questions come out of the same equality between the same two sockets. That is
 * the second reason to derive rather than list. mxgmn's model mirrors its
 * hand-written pairs into the two remaining directions explicitly, and a
 * tileset with a typo in it is a tileset whose supporter counts drift.
 */
export function buildPropagator(tiles: readonly Tile[]): Propagator {
	const T = tiles.length;
	const propagator: Int32Array[][] = [];

	for (let d = 0; d < 6; d++) {
		const back = (d + 3) % 6;
		const perTile: Int32Array[] = [];
		for (let t1 = 0; t1 < T; t1++) {
			const mine = tiles[t1]!.sockets[d]!;
			const matches: number[] = [];
			for (let t2 = 0; t2 < T; t2++) {
				if (tiles[t2]!.sockets[back] === mine) matches.push(t2);
			}
			perTile.push(Int32Array.from(matches));
		}
		propagator.push(perTile);
	}

	return propagator;
}

/** The six-bit open mask a placed tile contributes, for the level model. */
export function openMask(tile: Tile): number {
	let mask = 0;
	for (let d = 0; d < 6; d++) {
		if (tile.sockets[d]! !== SOCKET_WALL) mask |= 1 << d;
	}
	return mask;
}
