/*
 * Hexdelve — Lab 03: a keyframe player, and a blacksmith who uses it.
 *
 * The animation is not Three.js animation. Clips, sampling, crossfading,
 * layer masks, events, baking and the forward kinematics used to measure
 * stride are all in ../shared/anim.js, which contains no engine types at
 * all. Three is asked for exactly one thing: draw the meshes at the transforms
 * the pose says.
 *
 * The walk clip is generated by sampling lab 02's procedural walk and fitting
 * the fewest keys that reproduce it — pick "Walk — procedural" to compare the
 * two live. Every other clip is posed by hand, because a hammer strike is not
 * a sine wave.
 */

'use strict';

const { attachPanel, attachView, startZoom } = Hexdelve.ui;
const { HexField, groundMaterial, makeRandom, tintColor, SQRT3 } = Hexdelve.hex;
const { SKELETON, BONES, TIPS, UPPER_BODY, HIPS_Y } = Hexdelve.skeleton;
const { buildRig, buildSkeletonView, applyPose, applySparsePose } = Hexdelve.rigview;
const { buildBlacksmith } = Hexdelve.blacksmith;
const { walkPose, WALK_PERIOD, WALK_CONTACTS } = Hexdelve.walk;
const { AUTHORED } = Hexdelve.clips;
const { Player, bakeClip, samplePose, makeMask, measureGroundSpeed, DEG } = Hexdelve.anim;

const PI = Math.PI;
const TAU = PI * 2;

const GROUND_RADIUS = 7;
const ROAM_R = 3.2;
const GROUND_Y = 0.16; // the top face of a ground tile — where feet belong
const ANVIL = { x: 0, y: 1.03, z: 0 };
const WORK_SPOT = { x: -0.583, z: -0.619 };

const random = makeRandom(23);
const pick = (list) => list[Math.floor(random() * list.length)];

/* -------------------------------------------------------------- renderer -- */

const canvas = document.getElementById('scene');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;

const scene = new THREE.Scene();

const VIEW = 5.5;
const ISO_PITCH = Math.atan(1 / Math.SQRT2);
const CAM_DIST = 60;
const camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0.1, 200);

const view = { azimuth: (62 * PI) / 180, target: new THREE.Vector3(0, 1, 0), zoom: 1.7, zoomGoal: 1.7 };

function applyCamera() {
	camera.position.set(
		view.target.x + CAM_DIST * Math.cos(view.azimuth) * Math.cos(ISO_PITCH),
		view.target.y + CAM_DIST * Math.sin(ISO_PITCH),
		view.target.z + CAM_DIST * Math.sin(view.azimuth) * Math.cos(ISO_PITCH),
	);
	camera.lookAt(view.target);
	camera.zoom = view.zoom;
	camera.updateProjectionMatrix();
}

function resize() {
	const w = window.innerWidth;
	const h = window.innerHeight;
	renderer.setSize(w, h);
	const aspect = w / h;
	camera.left = -VIEW * aspect;
	camera.right = VIEW * aspect;
	camera.top = VIEW;
	camera.bottom = -VIEW;
	applyCamera();
}
window.addEventListener('resize', resize);

scene.add(new THREE.HemisphereLight(0xcfe0ee, 0x6a5a44, 0.62));
const sun = new THREE.DirectionalLight(0xfff1dc, 0.95);
sun.castShadow = true;
sun.shadow.mapSize.set(2048, 2048);
sun.shadow.camera.left = -10;
sun.shadow.camera.right = 10;
sun.shadow.camera.top = 10;
sun.shadow.camera.bottom = -10;
sun.shadow.camera.near = 1;
sun.shadow.camera.far = 90;
sun.shadow.bias = -0.0004;
sun.shadow.normalBias = 0.03;
{
	const a = (140 * PI) / 180;
	const el = (48 * PI) / 180;
	sun.position.set(30 * Math.cos(a) * Math.cos(el), 30 * Math.sin(el), 30 * Math.sin(a) * Math.cos(el));
}
scene.add(sun);
scene.add(sun.target);

/* ----------------------------------------------------------------- world -- */

const PAL = {
	grass: ['#79a256', '#71994f', '#82aa5e', '#6d944c'],
	worn: ['#a08a5e', '#98865f', '#a89365'],
	stone: ['#8d8d86', '#94948c', '#858680'],
	flower: ['#e8788a', '#e8d06a', '#f0f0e8', '#c77ddb'],
	spruce: ['#3f5f38', '#476b3e', '#385633'],
};

function buildWorld() {
	const field = new HexField();
	field.upright(0, -0.85, 0, SQRT3 * GROUND_RADIUS + 1.6, 0.86, new THREE.Color('#4a3b2c'), 90);

	const tiles = [];
	for (let q = -GROUND_RADIUS; q <= GROUND_RADIUS; q++) {
		for (let r = -GROUND_RADIUS; r <= GROUND_RADIUS; r++) {
			if ((Math.abs(q) + Math.abs(r) + Math.abs(q + r)) / 2 > GROUND_RADIUS) continue;
			const x = SQRT3 * (q + r / 2);
			const z = 1.5 * r;
			const d = Math.hypot(x, z);
			const worn = Math.abs(d - ROAM_R) < 0.95 || d < 2.0;
			field.upright(x, 0, z, 0.985, 0.16, tintColor(random, pick(worn ? PAL.worn : PAL.grass), 0.06));
			if (!worn) tiles.push({ x, z });
		}
	}

	for (const tile of tiles) {
		const roll = random();
		const dx = (random() - 0.5) * 0.9;
		const dz = (random() - 0.5) * 0.9;
		if (roll < 0.05) {
			field.upright(tile.x + dx, 0.16, tile.z + dz, 0.1, 0.1 + random() * 0.08, tintColor(random, pick(PAL.flower), 0.06), random() * 60);
		} else if (roll < 0.11) {
			field.upright(tile.x + dx, 0.16, tile.z + dz, 0.085, 0.2 + random() * 0.12, tintColor(random, '#5c8040', 0.06), random() * 60);
		}
	}

	// The anvil: stump, plate, body, horn. Its face sits at ANVIL.y, which is
	// the height the hammer clip is posed against.
	field.upright(0, 0.16, 0, 0.48, 0.44, tintColor(random, '#5c4127', 0.03), 14);
	field.upright(0, 0.6, 0, 0.3, 0.12, tintColor(random, '#3d4045', 0.02));
	field.lying('x', 0.02, 0.82, 0, 0.24, 0.72, tintColor(random, '#54585e', 0.02));
	field.lying('x', 0.5, 0.86, 0, 0.085, 0.28, tintColor(random, '#484c52', 0.02));

	// A rack of stock beside the anvil, and some scenery.
	field.lying('z', 1.5, 0.28, -0.4, 0.09, 1.3, tintColor(random, '#6b5334', 0.03));
	field.lying('z', 1.68, 0.28, -0.2, 0.09, 1.1, tintColor(random, '#6b5334', 0.03));
	spruce(field, -5.0, -3.6, 1.0);
	spruce(field, 5.4, 4.2, 0.85);
	field.upright(4.6, 0.16, -4.4, 0.5, 0.32, tintColor(random, pick(PAL.stone), 0.05), random() * 60);
	field.upright(-4.4, 0.16, 4.8, 0.38, 0.24, tintColor(random, pick(PAL.stone), 0.05), random() * 60);

	const mesh = field.build(groundMaterial());
	scene.add(mesh);
	return field.count;
}

function spruce(field, x, z, s) {
	const yaw = random() * 60;
	field.upright(x, 0.16, z, 0.26 * s, 1.1 * s, tintColor(random, '#6b4a2c', 0.03), yaw);
	for (const tier of [
		{ r: 1.5, h: 0.62, y: 0.95 },
		{ r: 1.15, h: 0.58, y: 1.62 },
		{ r: 0.8, h: 0.54, y: 2.26 },
		{ r: 0.45, h: 0.5, y: 2.86 },
	]) {
		field.upright(x, tier.y * s, z, tier.r * s, tier.h * s, tintColor(random, pick(PAL.spruce), 0.05), yaw + random() * 30);
	}
	field.upright(x, 3.34 * s, z, 0.18 * s, 0.42 * s, tintColor(random, pick(PAL.spruce), 0.05), yaw);
}

buildWorld();

/* ------------------------------------------------------ rig and character -- */

const actorGroup = new THREE.Group();
scene.add(actorGroup);

const rig = buildRig(SKELETON, actorGroup);
const character = buildBlacksmith(rig);
const skeletonView = buildSkeletonView(rig, SKELETON, TIPS);

/* ------------------------------------------------------------- animation -- */

// The walk is not authored: it is sampled from the procedural generator and
// fitted. Everything else in the menu was posed by hand.
const baked = bakeClip({
	name: 'walk',
	duration: WALK_PERIOD,
	loop: 'loop',
	samples: 240,
	tolerance: 1.2 * DEG,
	sample: (t) => walkPose((t / WALK_PERIOD) * TAU, 1),
	events: WALK_CONTACTS.map((t) => ({ t, name: 'step' })),
});

const player = new Player(BONES);
player.add(baked.clip);
for (const clip of AUTHORED) player.add(clip);

const base = player.layer();
const overlay = player.layer(makeMask(BONES, UPPER_BODY));
overlay.weight = 0;

// How fast the ground has to pass under each locomotion cycle for the feet not
// to slide — derived from the clip itself, not tuned by hand.
const GROUND_SPEED = {
	walk: measureGroundSpeed(SKELETON, (t) => samplePose(baked.clip, t), WALK_PERIOD),
	run: measureGroundSpeed(SKELETON, (t) => samplePose(player.get('run'), t), player.get('run').duration),
	walkProc: measureGroundSpeed(SKELETON, (t) => walkPose((t / WALK_PERIOD) * TAU, 1), WALK_PERIOD),
};

const MODES = {
	walk: { base: 'walk', loco: true },
	walkProc: { base: null, loco: true, procedural: true },
	run: { base: 'run', loco: true },
	hammer: { base: 'hammer' },
	swing: { base: 'swing' },
	jump: { base: 'jump' },
	duck: { base: 'duck' },
	idle: { base: 'idle' },
	'walk+hammer': { base: 'walk', loco: true, overlay: 'hammer' },
};

const ROUTINE = [
	{ clip: 'walk', time: 6.5 },
	{ clip: 'hammer', time: 5.6 },
	{ clip: 'walkProc', time: 5 },
	{ clip: 'swing', time: 4.8 },
	{ clip: 'run', time: 5.5 },
	{ clip: 'jump', time: 2.9 },
	{ clip: 'duck', time: 2.6 },
	{ clip: 'walk+hammer', time: 5.5 },
	{ clip: 'idle', time: 3.4 },
];

/* --------------------------------------------------------------- particles -- */

class Bits {
	constructor(count, { color, gravity, life, size, glow }) {
		this.items = [];
		this.gravity = gravity;
		this.life = life;
		this.size = size;
		for (let i = 0; i < count; i++) {
			const material = glow
				? new THREE.MeshBasicMaterial({ color, transparent: true, opacity: 0, depthWrite: false })
				: new THREE.MeshLambertMaterial({ color, transparent: true, opacity: 0, depthWrite: false });
			const mesh = new THREE.Mesh(character.meshes[0].geometry, material);
			mesh.visible = false;
			scene.add(mesh);
			this.items.push({ mesh, t: 0, vx: 0, vy: 0, vz: 0, spin: 0 });
		}
		this.next = 0;
	}

	spawn(x, y, z, n, spread, up) {
		for (let i = 0; i < n; i++) {
			const bit = this.items[this.next];
			this.next = (this.next + 1) % this.items.length;
			bit.t = this.life * (0.7 + random() * 0.3);
			bit.max = bit.t;
			bit.mesh.position.set(x, y, z);
			const a = random() * TAU;
			const r = spread * (0.3 + random());
			bit.vx = Math.cos(a) * r;
			bit.vz = Math.sin(a) * r;
			bit.vy = up * (0.5 + random());
			bit.spin = (random() - 0.5) * 12;
			bit.mesh.visible = true;
		}
	}

	update(dt) {
		for (const bit of this.items) {
			if (bit.t <= 0) continue;
			bit.t -= dt;
			if (bit.t <= 0) {
				bit.mesh.visible = false;
				continue;
			}
			bit.vy += this.gravity * dt;
			bit.mesh.position.x += bit.vx * dt;
			bit.mesh.position.y += bit.vy * dt;
			bit.mesh.position.z += bit.vz * dt;
			bit.mesh.rotation.y += bit.spin * dt;
			const u = bit.t / bit.max;
			const s = this.size * (0.4 + 0.6 * u);
			bit.mesh.scale.set(s, s * 0.8, s);
			bit.mesh.material.opacity = Math.min(1, u * 1.6) * 0.9;
		}
	}
}

const sparks = new Bits(26, { color: 0xffc46b, gravity: -7.5, life: 0.55, size: 0.045, glow: true });
const dust = new Bits(16, { color: 0xcfc3a8, gravity: -0.6, life: 0.8, size: 0.1 });

const tmpVec = new THREE.Vector3();

function hammerImpact() {
	if (!character.hammerHead) return;
	character.hammerHead.getWorldPosition(tmpVec);
	const onAnvil = Math.hypot(tmpVec.x - ANVIL.x, tmpVec.z - ANVIL.z) < 0.85 && Math.abs(tmpVec.y - ANVIL.y) < 0.5;
	if (onAnvil) {
		sparks.spawn(ANVIL.x, ANVIL.y + 0.06, ANVIL.z, 9, 1.9, 2.2);
	} else {
		dust.spawn(tmpVec.x, Math.max(0.18, tmpVec.y), tmpVec.z, 2, 0.5, 0.5);
	}
}

function footDust() {
	dust.spawn(actor.x + (random() - 0.5) * 0.3, 0.18, actor.z + (random() - 0.5) * 0.3, 2, 0.35, 0.5);
}

player.onEvent = (name) => {
	if (name === 'impact') hammerImpact();
	else if (name === 'step' || name === 'land') footDust();
	else if (name === 'launch') dust.spawn(actor.x, 0.18, actor.z, 3, 0.6, 0.7);
};

/* ------------------------------------------------------------------ actor -- */

const actor = {
	x: WORK_SPOT.x,
	z: WORK_SPOT.z,
	yaw: Math.atan2(ANVIL.x - WORK_SPOT.x, ANVIL.z - WORK_SPOT.z),
};
let phase = 'roam'; // 'roam' | 'travel' | 'perform'
let selected = 'hammer';
let procTheta = 0;
let procPrev = 0;
let finishedAt = -1;
let routineStep = 0;
let routineTimer = 0;

const wrapAngle = (a) => {
	while (a > PI) a -= TAU;
	while (a < -PI) a += TAU;
	return a;
};

function turnToward(targetYaw, dt, rate = 3.2) {
	const diff = wrapAngle(targetYaw - actor.yaw);
	const step = Math.max(-rate * dt, Math.min(rate * dt, diff));
	actor.yaw += step;
	return Math.abs(diff);
}

function steer(tx, tz, speed, dt) {
	const dx = tx - actor.x;
	const dz = tz - actor.z;
	const dist = Math.hypot(dx, dz);
	turnToward(Math.atan2(dx, dz), dt);
	const move = Math.min(speed * dt, dist);
	actor.x += Math.sin(actor.yaw) * move;
	actor.z += Math.cos(actor.yaw) * move;
	return dist;
}

function setMode(name, { user = false } = {}) {
	selected = name;
	ui.clip.value = name;
	if (user) ui.auto.checked = false;
	const mode = MODES[name];
	phase = mode.loco ? 'roam' : ui.stay.checked ? 'perform' : 'travel';
	finishedAt = -1;
	if (mode.overlay) {
		overlay.play(mode.overlay, { fade: 0.25 });
		overlay.weight = 1;
	} else {
		overlay.weight = 0;
	}
	renderTimeline();
	renderStats();
}

/* -------------------------------------------------------------------- ui -- */

const ui = {
	clip: document.getElementById('clip'),
	speed: document.getElementById('speed'),
	speedOut: document.getElementById('speedOut'),
	play: document.getElementById('play'),
	auto: document.getElementById('auto'),
	stay: document.getElementById('stay'),
	showChar: document.getElementById('showChar'),
	showSkel: document.getElementById('showSkel'),
	follow: document.getElementById('follow'),
	tlName: document.getElementById('tlName'),
	tlTime: document.getElementById('tlTime'),
	tlRows: document.getElementById('tlRows'),
	tlScroll: document.getElementById('tlScroll'),
	tlPlayhead: document.getElementById('tlPlayhead'),
	stats: document.getElementById('stats'),
};

function applyVisibility() {
	const showC = ui.showChar.checked;
	const showS = ui.showSkel.checked;
	const xray = showC && showS;
	for (const m of character.meshes) m.visible = showC;
	for (const m of skeletonView.meshes) m.visible = showS;
	for (const mat of character.materials.values()) {
		mat.transparent = xray;
		mat.opacity = xray ? 0.32 : 1;
		mat.depthWrite = !xray;
		mat.needsUpdate = true;
	}
}

function activeClip() {
	const mode = MODES[selected];
	if (mode.procedural) return null;
	return player.get(phase === 'travel' ? 'walk' : mode.base);
}

function renderTimeline() {
	const clip = activeClip();
	ui.tlRows.innerHTML = '';
	if (!clip) {
		ui.tlName.textContent = 'procedural — no keys';
		ui.tlRows.innerHTML =
			'<p class="tl-note">Nothing to show: the pose is evaluated from a formula every frame, so there is no data to scrub.</p>';
		ui.tlPlayhead.style.display = 'none';
		return;
	}
	ui.tlPlayhead.style.display = '';
	ui.tlName.textContent = `${clip.name} · ${clip.duration.toFixed(2)}s · ${clip.loop}`;

	if (clip.events.length) {
		const row = document.createElement('div');
		row.className = 'tl-row events';
		row.innerHTML = '<span class="tl-label">events</span><span class="tl-track"></span>';
		const track = row.lastChild;
		for (const e of clip.events) {
			const dot = document.createElement('i');
			dot.className = 'ev';
			dot.style.left = `${(e.t / clip.duration) * 100}%`;
			dot.title = `${e.name} @ ${e.t.toFixed(2)}s`;
			track.appendChild(dot);
		}
		ui.tlRows.appendChild(row);
	}

	for (const boneName of BONES) {
		const track = clip.tracks[boneName];
		if (!track) continue;
		const row = document.createElement('div');
		row.className = 'tl-row';
		row.innerHTML = `<span class="tl-label">${boneName}</span><span class="tl-track"></span>`;
		const lane = row.lastChild;
		for (const ch of ['rot', 'pos']) {
			if (!track[ch]) continue;
			for (const key of track[ch]) {
				const dot = document.createElement('i');
				if (ch === 'pos') dot.className = 'pos';
				dot.style.left = `${(key.t / clip.duration) * 100}%`;
				lane.appendChild(dot);
			}
		}
		ui.tlRows.appendChild(row);
	}
}

function renderStats() {
	const clip = activeClip();
	const rows = [];
	if (clip) {
		let keys = 0;
		let tracks = 0;
		for (const boneName in clip.tracks) {
			tracks++;
			for (const ch of ['rot', 'pos']) if (clip.tracks[boneName][ch]) keys += clip.tracks[boneName][ch].length;
		}
		rows.push(['Source', clip.name === 'walk' ? 'baked from the walk function' : 'posed by hand']);
		rows.push(['Keys', `${keys} over ${tracks} bones`]);
		if (clip.name === 'walk') {
			rows.push(['Fit', `${baked.stats.samples} samples → ${baked.stats.keys} keys`]);
			rows.push(['Error', `≤ ${(baked.stats.maxError / DEG).toFixed(2)}°`]);
		}
	} else {
		rows.push(['Source', 'evaluated live, no keys']);
	}
	const speed = GROUND_SPEED[MODES[selected].loco ? (MODES[selected].procedural ? 'walkProc' : MODES[selected].base) : null];
	if (speed) rows.push(['Stride', `${speed.toFixed(2)} m/s from the feet`]);
	ui.stats.innerHTML = rows.map(([k, v]) => `<dt>${k}</dt><dd>${v}</dd>`).join('');
}

ui.clip.addEventListener('change', () => setMode(ui.clip.value, { user: true }));
ui.speed.addEventListener('input', () => {
	ui.speedOut.textContent = `${(+ui.speed.value).toFixed(1)}×`;
});
ui.stay.addEventListener('change', () => setMode(selected));
ui.showChar.addEventListener('change', applyVisibility);
ui.showSkel.addEventListener('change', applyVisibility);

// Scrubbing the timeline drives the clip directly — the clearest way to see
// that a clip is just a function of time.
let scrubbing = false;

function scrubTo(clientX) {
	const lane = ui.tlRows.querySelector('.tl-track');
	const clip = activeClip();
	if (!lane || !clip) return;
	const rect = lane.getBoundingClientRect();
	const frac = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
	base.time = frac * clip.duration;
}

ui.tlScroll.addEventListener('pointerdown', (e) => {
	if (!activeClip()) return;
	scrubbing = true;
	ui.play.checked = false;
	ui.tlScroll.setPointerCapture(e.pointerId);
	scrubTo(e.clientX);
});
ui.tlScroll.addEventListener('pointermove', (e) => scrubbing && scrubTo(e.clientX));
ui.tlScroll.addEventListener('pointerup', () => {
	scrubbing = false;
});

/* -------------------------------------------------------------- controls -- */

// Orbit, pan and zoom, from a mouse or from fingers — see ../shared/ui.js.
// The panel opens and closes from ../shared/ui.js, which also reads ?panel=.
attachPanel();

attachView(canvas, view, {
	applyCamera: applyCamera,
	viewHeight: VIEW,
	pitch: ISO_PITCH,
	zoom: [0.6, 5],
	onPan: function () {
		ui.follow.checked = false;
	},
});

/* --------------------------------------------- secondary motion (apron) -- */

// Not keyframed and not baked: a spring chasing the thighs. Cloth, hair and
// hit reactions belong on top of clips like this, which is the layering the
// whole system is built for.
let apronAngle = 0;
let apronVel = 0;

function updateApron(dt) {
	const lead = Math.min(rig.bones.hipL.rotation.x, rig.bones.hipR.rotation.x);
	const target = lead * 0.5;
	const k = 90;
	const damping = 13;
	apronVel += (target - apronAngle) * k * dt - apronVel * damping * dt;
	apronAngle += apronVel * dt;
	character.apron.quaternion.setFromEuler(new THREE.Euler(PI / 2 - 0.03 + apronAngle, PI / 6, 0));
}

/* ------------------------------------------------------------------ loop -- */

function updateActor(dt, timeScale) {
	const mode = MODES[selected];
	const speedKey = mode.procedural ? 'walkProc' : mode.base;
	const groundSpeed = (GROUND_SPEED[speedKey] || GROUND_SPEED.walk) * timeScale;

	if (phase === 'roam') {
		const angle = Math.atan2(actor.x, actor.z);
		const carrot = angle + 0.5;
		steer(ROAM_R * Math.sin(carrot), ROAM_R * Math.cos(carrot), groundSpeed, dt);
	} else if (phase === 'travel') {
		// Slow down on the final approach. A constant speed with a limited turn
		// rate just orbits the target: the turn radius is v/ω, so the way to
		// arrive is to shed v.
		const remaining = Math.hypot(WORK_SPOT.x - actor.x, WORK_SPOT.z - actor.z);
		const ease = Math.max(0.22, Math.min(1, remaining / 0.9));
		const dist = steer(WORK_SPOT.x, WORK_SPOT.z, GROUND_SPEED.walk * timeScale * ease, dt);
		// Converge the last few centimetres directly. The strike pose has a
		// fixed reach, so stopping "near enough" is what makes the hammer miss
		// the anvil — the honest fix for that is IK on the arm, not a tighter
		// tolerance, but until then he has to arrive where the pose expects.
		if (dist < 0.35) {
			const k = Math.min(1, dt * 3);
			actor.x += (WORK_SPOT.x - actor.x) * k;
			actor.z += (WORK_SPOT.z - actor.z) * k;
		}
		if (dist < 0.08) {
			phase = 'perform';
			finishedAt = -1;
			renderTimeline();
			renderStats();
		}
	} else {
		turnToward(Math.atan2(ANVIL.x - actor.x, ANVIL.z - actor.z), dt, 2.2);
	}

	actorGroup.position.set(actor.x, GROUND_Y, actor.z);
	actorGroup.rotation.y = actor.yaw;
}

function updateRoutine(dt) {
	if (!ui.auto.checked) return;
	if (phase === 'travel') return; // walking over does not count against the step
	routineTimer += dt;
	const step = ROUTINE[routineStep];
	if (routineTimer >= step.time) {
		routineTimer = 0;
		routineStep = (routineStep + 1) % ROUTINE.length;
		setMode(ROUTINE[routineStep].clip);
	}
}

let last = performance.now();
let elapsed = 0;

function frame(now) {
	const dt = Math.min((now - last) / 1000, 0.06);
	last = now;
	elapsed += dt;

	const timeScale = +ui.speed.value;
	const playing = ui.play.checked;
	const mode = MODES[selected];

	updateRoutine(dt);
	updateActor(playing ? dt : 0, timeScale);

	if (mode.procedural && phase !== 'travel') {
		// No clip, no player: evaluate the walk straight into the rig.
		if (playing) procTheta += dt * timeScale * (TAU / WALK_PERIOD);
		applySparsePose(rig, walkPose(procTheta, 1, elapsed));
		// Contacts have to be detected by hand here; a clip would just carry
		// an event track.
		for (const contact of WALK_CONTACTS) {
			const target = (contact / WALK_PERIOD) * TAU;
			if (Math.floor((procTheta - target) / TAU) !== Math.floor((procPrev - target) / TAU)) footDust();
		}
		procPrev = procTheta;
		overlay.weight = 0;
	} else {
		const wanted = phase === 'travel' ? 'walk' : mode.base;
		base.paused = !playing;
		base.play(wanted, { fade: 0.24, speed: timeScale });
		overlay.paused = !playing;
		if (mode.overlay && phase !== 'travel') overlay.play(mode.overlay, { fade: 0.25, speed: timeScale });
		player.update(dt);
		applyPose(rig, BONES, player.pose);

		// Non-looping clips hold their last pose; replay them so the lab keeps
		// showing something.
		if (base.finished && phase === 'perform') {
			if (finishedAt < 0) finishedAt = elapsed;
			else if (elapsed - finishedAt > 0.9) {
				finishedAt = -1;
				base.play(wanted, { restart: true, fade: 0.18, speed: timeScale });
			}
		}
	}

	updateApron(dt);
	sparks.update(dt);
	dust.update(dt);

	// Timeline playhead.
	const clip = activeClip();
	if (clip) {
		const frac = clip.duration > 0 ? base.time / clip.duration : 0;
		ui.tlPlayhead.style.left = `calc(62px + (100% - 69px) * ${frac.toFixed(4)})`;
		ui.tlTime.textContent = `${base.time.toFixed(2)}s`;
	} else {
		ui.tlTime.textContent = `${((procTheta / TAU) * WALK_PERIOD).toFixed(2)}s`;
	}

	if (ui.follow.checked) {
		view.target.x += (actor.x - view.target.x) * Math.min(1, dt * 2.6);
		view.target.z += (actor.z - view.target.z) * Math.min(1, dt * 2.6);
		view.target.y += (HIPS_Y + 0.15 - view.target.y) * Math.min(1, dt * 2.6);
		applyCamera();
	}
	if (Math.abs(view.zoom - view.zoomGoal) > 1e-4) {
		view.zoom += (view.zoomGoal - view.zoom) * Math.min(1, dt * 10);
		applyCamera();
	}

	renderer.render(scene, camera);
	requestAnimationFrame(frame);
}

/* ----------------------------------------------------------------- start -- */

{
	// A portrait phone sees a much narrower slice of the world than a desktop
	// window does; open zoomed out to match.
	view.zoom = view.zoomGoal = startZoom(view.zoom);

	const qs = new URLSearchParams(location.search);
	if (qs.has('clip')) selected = qs.get('clip');
	if (qs.has('auto')) ui.auto.checked = qs.get('auto') !== '0';
	if (qs.has('stay')) ui.stay.checked = qs.get('stay') !== '0';
	if (qs.has('char')) ui.showChar.checked = qs.get('char') !== '0';
	if (qs.has('skel')) ui.showSkel.checked = qs.get('skel') !== '0';
	if (qs.has('speed')) ui.speed.value = qs.get('speed');
	if (qs.has('zoom')) view.zoom = view.zoomGoal = +qs.get('zoom');
	if (qs.has('follow')) ui.follow.checked = qs.get('follow') !== '0';
}

// Handy from the console: lab.base.time = 0.5, lab.setMode('swing'), …
window.lab = { player, base, overlay, rig, character, actor, view, baked, GROUND_SPEED, setMode };

ui.speedOut.textContent = `${(+ui.speed.value).toFixed(1)}×`;
applyVisibility();
setMode(selected);
if (MODES[selected].loco) phase = 'roam';
resize();
requestAnimationFrame(frame);
